### ISSUE TITLE
[Bug]: nextflow pipeline running failed

### ISSUE THREAD

**Issue by ChenDepp** [epi2me-labs/wf-pore-c#10]
### What happened?

hi, when in running this pipeline with nextflow, it report error !
    please tell me how to solve it ?
  thank you!

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

nextflow version 22.10.7.5854

### Relevant log output

```shell
fc477195-b172-4eda-933b-c91df3d5874e
[10:14:05 - AnntateBAM] Processing reads from -
[10:14:05 - Digest    ] Digesting concatemers from [<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>].
Traceback (most recent call last):
  File "/home/epi2melabs/conda/bin/pore-c-py", line 10, in <module>
    sys.exit(run_main())
  File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 382, in run_main
    args.func(args)
  File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 230, in digest_bam
    with pysam.AlignmentFile(
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 952, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
[M::bam2fq_mainloop] discarded 0 singletons
[M::bam2fq_mainloop] processed 0 reads
[M::main::9.328*0.98] loaded/built the index for 711 target sequence(s)
[M::mm_mapopt_update::11.659*0.98] mid_occ = 748
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 711
[M::mm_idx_stat::12.572*0.99] distinct minimizers: 100226728 (37.11% are singletons); average occurrences: 5.897; average spacing: 5.582; total length: 3299210039
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ay -t 40 -x map-ont reference.fasta.mmi -
[M::main] Real time: 13.322 sec; CPU: 13.137 sec; Peak RSS: 8.103 GB
[10:14:18 - AnntateAln] Found 0 monomers in 0 concatemers.
[10:14:18 - AnntateBAM] Finished BAM parsing.

------------------------------------------------------------------
    Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 10, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/cli/cload.py", line 551, in pairs
      f_in = get_handle(pairs_path, mode='r', compression='infer')[0]
  TypeError: 'IOHandles' object is not subscriptable
```

**Comment by cjw85** [comment]
Hi @ChenDepp,

Can you please provide the command you have attempted to run, the error:

```
ValueError: file does not contain alignment data
```

suggests you are not providing a valid input file.

**Comment by ChenDepp** [comment]
@cjw85 
 thanks for your reply, the first figure is nextflow command; second figure and three figure is error information and process command
![3](https://github.com/epi2me-labs/wf-pore-c/assets/48479509/8e01dd3d-cf84-4708-b433-fdf0b10936f9)
![1](https://github.com/epi2me-labs/wf-pore-c/assets/48479509/b67055a4-d01e-4d87-a073-c6c3852b2556
![2](https://github.com/epi2me-labs/wf-pore-c/assets/48479509/20b76114-7532-4010-aca0-f523cf60f8bf)
)

**Comment by ChenDepp** [comment]
hi @cjw85 
    I found out that this error is caused by third-party delivery software (Get_handle function returns IHandles object, which does not support Slice operation. (The object may not implement __getitem__ special method). So I changed cooler/cli/cload.py . Then I re-run it and it can successfully run the process pairsToCooler.
  
       Finally, I want to know, how to set the sample name in the sample_sheet? （I didn't provide sample_sheet so I go 'null' string as prefix name of output file） If I have multiple independent samples, I need to run this process, how to set it in sample_sheet?
       I don't quite understand what information is stored in the output file, for example, what does each line in sample_name.pairs.gz（As shown below） mean? I understand deposits are sites where there is interaction; do you have detailed documentation on the results
    ![1](https://github.com/epi2me-labs/wf-pore-c/assets/48479509/615d795c-e08f-48b8-800a-8259b9d610c4)

      I am very interested in your pore-c-py software and would like to know more details about it, have you published an article about this software? I want to understand and learn the methods and principles of software
    thanks you, waiting for you reply !

**Comment by sarahjeeeze** [comment]
Hi, the cload.py error was resolved in a more recent version of the workflow, we have also updated the documentation to provide links to explanations for the outputs including the pairs format. eg. https://pairtools.readthedocs.io/en/latest/formats.html Let us know if you have any questions. You can see an example of how to use sample sheet to provide aliases for your input data here https://github.com/epi2me-labs/wf-pore-c/blob/master/test_data/sample_sheet.csv

**Comment by sarahjeeeze** [comment]
Closing through lack of response, and issue should be resolved.
