### ISSUE TITLE
pairsToCooler

### ISSUE THREAD

**Issue by Oksanak22** [epi2me-labs/wf-pore-c#25]
### Operating System

Ubuntu 22.04

### Workflow Version

v.0.0.8

### Workflow Execution

Other (please describe)

### EPI2ME Version

compute canada

### CLI command run

I add I added in nextflow.config file of version 0.0.8 the "ignore" statement 

    apptainer {
        apptainer {
            enabled = true
            autoMounts = true
            process.executor = 'slurm'
            process.beforeScript = 'module load apptainer'
            process.cpus = 1
            process.memory = "8G"
            process.time = "16h"
       	    process.errorStrategy = 'ignore'
        }
This  "ignore" for all the failed analyses for the "pairsToCooler" steps so it moved on with other tests. 

### Workflow Execution - CLI Execution Profile

None

### What happened?

I run once this pipeline with this modification. But when I changed the dataset this pipeline failed. 
This is the error:
Command error:
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
  [12:03:07 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow-glue", line 7, in <module>
      cli()
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow_glue/report.py", line 31, in main
      fastcat.SeqSummary(args.stats)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/ezcharts/components/fastcat.py", line 47, in __init__
      df_all = load_stats(seq_summary, format='fastcat')
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/ezcharts/components/fastcat.py", line 375, in load_stats
      df['start_time'] = df.start_time.dt.tz_localize(None)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
      return object.__getattribute__(self, name)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/accessor.py", line 182, in __get__
      accessor_obj = self._accessor(obj)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/indexes/accessors.py", line 512, in __new__
      raise AttributeError("Can only use .dt accessor with datetimelike values")
  AttributeError: Can only use .dt accessor with datetimelike values

### Relevant log output

```shell
INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
  [12:03:07 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow-glue", line 7, in <module>
      cli()
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/project/6058390/oksanak/wf-pore-C/wf-pore-c-0.1.0/bin/workflow_glue/report.py", line 31, in main
      fastcat.SeqSummary(args.stats)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/ezcharts/components/fastcat.py", line 47, in __init__
      df_all = load_stats(seq_summary, format='fastcat')
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/ezcharts/components/fastcat.py", line 375, in load_stats
      df['start_time'] = df.start_time.dt.tz_localize(None)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/generic.py", line 5902, in __getattr__
      return object.__getattribute__(self, name)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/accessor.py", line 182, in __get__
      accessor_obj = self._accessor(obj)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/core/indexes/accessors.py", line 512, in __new__
      raise AttributeError("Can only use .dt accessor with datetimelike values")
  AttributeError: Can only use .dt accessor with datetimelike values
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for reporting this. We will look in to it and get back to you.

**Comment by sarahjeeeze** [comment]
Hi, I've been unable to recreate the error, would you be able to provide the command you used to run the workflow?

**Comment by Oksanak22** [comment]
Hello, actually with the latest version v0.1.1 I ran one data set successfully, and another one - failed, even though I was able to run it successfully with v.0.0.8. The error is as following:

executor >  slurm (2999)
[16/e47954] process > POREC:fastcat (1)              [100%] 1 of 1 ✔
[1b/c659f2] process > POREC:index_ubam (1)           [100%] 1 of 1 ✔
[75/96fc8f] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[1c/b4ba93] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[df/b8966b] process > POREC:digest_align_annotate... [100%] 995 of 995 ✔
[-        ] process > POREC:haplotag_alignments      -
[63/36247e] process > POREC:merge_coordsorted_bam... [100%] 1 of 1 ✔
[3e/6c738f] process > POREC:merge_namesorted_bams... [100%] 1 of 1 ✔
[84/a31117] process > POREC:create_restriction_be... [100%] 1 of 1 ✔
[a6/adb729] process > POREC:to_pairs_file (995)      [100%] 995 of 995, faile...
[c7/883b0c] process > POREC:pairsToCooler (994)      [100%] 994 of 994 ✔
[3e/b3a1fe] process > POREC:merge_mcools (1)         [100%] 1 of 1 ✔
[05/99d3d2] process > POREC:merge_pairs (1)          [100%] 1 of 1 ✔
[19/e9d7ba] process > POREC:merge_pairs_stats (1)    [100%] 1 of 1 ✔
[9f/07ad61] process > POREC:pair_stats_report (1)    [100%] 1 of 1 ✔
[0c/a1ca5c] process > POREC:merge_parquets_to_dat... [100%] 1 of 1 ✔
[de/9190fd] process > POREC:getVersions              [100%] 1 of 1 ✔
[f5/37beb6] process > POREC:getParams                [100%] 1 of 1 ✔
[0e/1c2e4a] process > POREC:makeReport (1)           [100%] 1 of 1 ✔

Completed at: 31-Aug-2023 22:16:35
Duration    : 13h 23m 28s
CPU hours   : 124.0 (0% failed)
Succeeded   : 2'998


And I run this"
module load apptainer/1.1.8 java/17.0.2 nextflow/23.04.3



nextflow run main.nf -c nextflow.config \
 --fastq /home/oksanak/projects/def-icestari/oksanak/pore-c-py/N129N145PF \
 --ref /home/oksanak/projects/def-icestari/oksanak/pore-c-py/T427_63_2018_no_unitigs_genome.fasta \
 --cutter HindIII \
 --mcool_resolutions 1000,2000,3000 \
 --pairs  --chromunity --mcool \
 --out_dir N129N145_results-01-09-23 \
 --hi_c \
 -profile apptainer \
-resume

 on a Beluga cluster.

**Comment by Oksanak22** [comment]
hello!
This is an error for v0.1.1 with all "ignore" corrections in a nextflow.log:
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00002ba20c81e177, pid=9080, tid=24257
#
# JRE version: OpenJDK Runtime Environment 18.9 (11.0.16+8) (build 11.0.16+8)
# Java VM: OpenJDK 64-Bit Server VM 18.9 (11.0.16+8, mixed mode, tiered, compressed oops, serial gc, linux-amd64)
# Problematic frame:
# v  ~StubRoutines::jbyte_disjoint_arraycopy
#
# Core dump will be written. Default location: /project/wf-pore-C/wf-pore-c-0.1.0/core.9080
#
# An error report file with more information is saved as:
# /project/wf-pore-C/wf-pore-c-0.1.0/hs_err_pid9080.log
Compiled method (c2) 6287342 8185   !   4       java.nio.DirectByteBuffer::put (151 bytes)
 total in heap  [0x00002ba2146b2110,0x00002ba2146b2a58] = 2376
 relocation     [0x00002ba2146b2288,0x00002ba2146b22b0] = 40
 main code      [0x00002ba2146b22c0,0x00002ba2146b2600] = 832
 stub code      [0x00002ba2146b2600,0x00002ba2146b2618] = 24
 oops           [0x00002ba2146b2618,0x00002ba2146b2620] = 8
 metadata       [0x00002ba2146b2620,0x00002ba2146b2690] = 112
 scopes data    [0x00002ba2146b2690,0x00002ba2146b2948] = 696
 scopes pcs     [0x00002ba2146b2948,0x00002ba2146b2a38] = 240
 dependencies   [0x00002ba2146b2a38,0x00002ba2146b2a40] = 8
 nul chk table  [0x00002ba2146b2a40,0x00002ba2146b2a58] = 24
Compiled method (c2) 6287342 11454       4       com.esotericsoftware.minlog.Log$Logger::log (158 bytes)
 total in heap  [0x00002ba214888410,0x00002ba21488b118] = 11528
 relocation     [0x00002ba214888588,0x00002ba214888698] = 272
 main code      [0x00002ba2148886a0,0x00002ba21488a0e0] = 6720
 stub code      [0x00002ba21488a0e0,0x00002ba21488a150] = 112
 oops           [0x00002ba21488a150,0x00002ba21488a178] = 40
 metadata       [0x00002ba21488a178,0x00002ba21488a248] = 208
 scopes data    [0x00002ba21488a248,0x00002ba21488ab48] = 2304
 scopes pcs     [0x00002ba21488ab48,0x00002ba21488aef8] = 944
 dependencies   [0x00002ba21488aef8,0x00002ba21488af00] = 8
 handler table  [0x00002ba21488af00,0x00002ba21488b080] = 384
 nul chk table  [0x00002ba21488b080,0x00002ba21488b118] = 152
Compiled method (c1) 6287343 12847       3       org.iq80.leveldb.impl.MMapLogWriter::newLogRecordHeader (77 bytes)
 total in heap  [0x00002ba20e94ca10,0x00002ba20e94efc8] = 9656
 relocation     [0x00002ba20e94cb88,0x00002ba20e94cd90] = 520
 main code      [0x00002ba20e94cda0,0x00002ba20e94e4e0] = 5952
 stub code      [0x00002ba20e94e4e0,0x00002ba20e94e5a0] = 192
 oops           [0x00002ba20e94e5a0,0x00002ba20e94e5b0] = 16
 metadata       [0x00002ba20e94e5b0,0x00002ba20e94e660] = 176
 scopes data    [0x00002ba20e94e660,0x00002ba20e94eab0] = 1104
 scopes pcs     [0x00002ba20e94eab0,0x00002ba20e94ef30] = 1152
 dependencies   [0x00002ba20e94ef30,0x00002ba20e94ef38] = 8
 nul chk table  [0x00002ba20e94ef38,0x00002ba20e94efc8] = 144

Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
/var/spool/slurmd/job11131832/slurm_script: line 24:  9080 Aborted                 (core dumped) nextflow run main.nf -c nextflow.config --fastq /home/wf-pore-C/wf-pore-c-0.1.0/N141N144.fastq --ref >

**Comment by sarahjeeeze** [comment]
Hi, this seems to be something to do with your environment. I think you will need to contact your system administrators. It might just be running out of memory at the end. On the run where it worked did you get the outputs and a report?

**Comment by Oksanak22** [comment]
Hi. Yes, with a successful run, I got all the output files, including the report. How much memory do I need to have to be able to run a pipeline with no issues?

**Comment by sarahjeeeze** [comment]
Hi, you can check how much memory the successful run used by looking in the execution folder and looking at the timeline or report.html and looking at the memory resources. It depends how big the chunks are as to how much memory a single task will use, for me it varied between eg. 60gb with chunks turned off and 15gb per task if you are doing 50000 reads sized chunks but make sure not to set global threads too high as that will cause it to run too many tasks at once which will cause a memory error. Leave global threads low at eg. 16.
