### ISSUE TITLE
[Bug]:   pore-c-py digest "concatemers.bam" "NlaIII" "SRR1158941.monomers.bam"

### ISSUE THREAD

**Issue by tahashmi** [epi2me-labs/wf-pore-c#3]
[run.txt](https://github.com/epi2me-labs/wf-pore-c/files/11065534/run.txt)
### What happened?

A bug happened!

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

latest singularity nextflow wf-pore-c

### Relevant log output

```shell
Hi,

I am getting following error when running the following command:


#! /bin/bash

#SBATCH --partition=norm
#SBATCH --cpus-per-task=56
#SBATCH --output=run.out
#SBATCH --time=72:00:00
#SBATCH --mem=256g

module load samtools
module load minimap2
module load nextflow
module load singularity
module load GATK/4.3.0.0

nextflow run epi2me-labs/wf-pore-c --ubam /data/tahmad/devel/porec/SRR1158941.bam --ref /data/tahmad/COLO829/alignment/grch38_chr.fasta --vcf /data/Shiraishi_cell_lines/phasing_pmdv/HCC1954BL/PEPPER_MARGIN_DEEPVARIANT_FINAL_OUTPUT.phased.vcf.gz --mcool_resolutions 10,20,30  -profile singularity --cutter  'NlaIII'
```

```
[5a/6fb466] process > POREC:check_input:chunk_uba... [100%] 1 of 1 ✔
[62/e56883] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[15/c908fd] process > POREC:digest_concatemers (68)  [  2%] 18 of 847
[-        ] process > POREC:map_monomers             [  0%] 0 of 18
[-        ] process > POREC:annotate_monomers        -
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
Error executing process > 'POREC:digest_concatemers (63)'

Caused by:
  Process `POREC:digest_concatemers (63)` terminated with an error exit status (2)

Command executed:

  pore-c-py digest "concatemers.bam" "NlaIII" "SRR1158941.monomers.bam"

Command exit status:
  2

Command output:
  (empty)

Command error:
  runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc0000da790 sp=0xc0000da770 pc=0x555555e91996
  runtime.goparkunlock(...)
        runtime/proc.go:369
  runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:278 +0x8e fp=0xc0000da7c8 sp=0xc0000da790 pc=0x555555e7b6ce
  runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc0000da7e0 sp=0xc0000da7c8 pc=0x555555e70286
  runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc0000da7e8 sp=0xc0000da7e0 pc=0x555555ec16a1
  created by runtime.gcenable
        runtime/mgc.go:178 +0x6b

  goroutine 19 [GC scavenge wait]:
  runtime.gopark(0xc00018e000?, 0x555556d91f50?, 0x1?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc0000daf70 sp=0xc0000daf50 pc=0x555555e91996
  runtime.goparkunlock(...)
        runtime/proc.go:369
  runtime.(*scavengerState).park(0x5555579d0180)
        runtime/mgcscavenge.go:389 +0x53 fp=0xc0000dafa0 sp=0xc0000daf70 pc=0x555555e796f3
  runtime.bgscavenge(0x0?)
        runtime/mgcscavenge.go:617 +0x45 fp=0xc0000dafc8 sp=0xc0000dafa0 pc=0x555555e79ce5
  runtime.gcenable.func2()
        runtime/mgc.go:179 +0x26 fp=0xc0000dafe0 sp=0xc0000dafc8 pc=0x555555e70226
  runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc0000dafe8 sp=0xc0000dafe0 pc=0x555555ec16a1
  created by runtime.gcenable
        runtime/mgc.go:179 +0xaa

  rax    0x0
  rbx    0x2aaaab6f7868
  rcx    0xffffffffffffffff
  rdx    0x6
  rdi    0x11cf9
  rsi    0x11cf9
  rbp    0x555556dac6a6
  rsp    0x7fffffffe4f8
  r8     0xa
  r9     0x2aaaaaaf0200
r10    0x8
  r11    0x206
  r12    0x555557b97050
  r13    0x178
  r14    0xc0000061a0
  r15    0x2aaad270914e
  rip    0x2aaaab366277
  rflags 0x206
  cs     0x33
  fs     0x0
  gs     0x0

Work dir:
  /vf/users/KolmogorovLab/tahmad/devel/porec/work/f2/9894bbb40dc6ec083aa1ff31e1db9f

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`



executor >  local (77)
[5a/6fb466] process > POREC:check_input:chunk_uba... [100%] 1 of 1 ✔
[62/e56883] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[f2/9894bb] process > POREC:digest_concatemers (63)  [  2%] 19 of 847, failed: 1
[-        ] process > POREC:map_monomers             [  0%] 0 of 18
[-        ] process > POREC:annotate_monomers        -
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
Error executing process > 'POREC:digest_concatemers (63)'

Caused by:
  Process `POREC:digest_concatemers (63)` terminated with an error exit status (2)

Command executed:

  pore-c-py digest "concatemers.bam" "NlaIII" "SRR1158941.monomers.bam"

Command exit status:
  2

Command output:
  (empty)

Command error:
  runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc0000da790 sp=0xc0000da770 pc=0x555555e91996
  runtime.goparkunlock(...)
        runtime/proc.go:369
  runtime.bgsweep(0x0?)
        runtime/mgcsweep.go:278 +0x8e fp=0xc0000da7c8 sp=0xc0000da790 pc=0x555555e7b6ce
  runtime.gcenable.func1()
        runtime/mgc.go:178 +0x26 fp=0xc0000da7e0 sp=0xc0000da7c8 pc=0x555555e70286
  runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc0000da7e8 sp=0xc0000da7e0 pc=0x555555ec16a1
  created by runtime.gcenable
        runtime/mgc.go:178 +0x6b

  goroutine 19 [GC scavenge wait]:
  runtime.gopark(0xc00018e000?, 0x555556d91f50?, 0x1?, 0x0?, 0x0?)
        runtime/proc.go:363 +0xd6 fp=0xc0000daf70 sp=0xc0000daf50 pc=0x555555e91996
  runtime.goparkunlock(...)
        runtime/proc.go:369
  runtime.(*scavengerState).park(0x5555579d0180)
        runtime/mgcscavenge.go:389 +0x53 fp=0xc0000dafa0 sp=0xc0000daf70 pc=0x555555e796f3

```
```

**Comment by cjw85** [comment]
Hi @tahashmi,

I'm a little perplexed by the errors you have: they appear to be from the Go language runtime but the workflow does not use any Go code.

Also it appears that you are not using the latest version. Your log says v0.0.1, but the latest version is v0.0.2.

**Comment by tahashmi** [comment]
Ah! right. Is there docker/singularity available for latest v0.0.2 one? So what's alternate approach of using nextflow to avoid singularity/docker containers then? I can use my own laptop.

**Comment by sarahjeeeze** [comment]
Hi, Did you find a solution for this in the end?

**Comment by sarahjeeeze** [comment]
Closing through lack of response, feel free to open another issue if you are still having troubles with the environment,
