### ISSUE TITLE
Process `POREC:merge_pairs (1)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by SwenDiepstraten** [epi2me-labs/wf-pore-c#33]
### Ask away!

Hello,

I am encountering an error when running the workflow and I do not know how to fix it. the command I am running is as follows:   nextflow run wf-pore-c \
        --cutter 'NlaIII' \
        --ref 'assembly.fasta' \
	--hi_c \
	--threads 32 \
	--out_dir 'output' \
	-profile singularity \
	-c 'pore-c_config.config' \
	--fastq 'combined_pore-c.fastq.gz'

the full error message is:
executor >  local (3834)
[d0/9a7cb2] process > POREC:fastcat (1)              [100%] 1 of 1 âœ”
[64/ddc92b] process > POREC:index_ubam (1)           [100%] 1 of 1 âœ”
[8d/fc3aec] process > POREC:prepare_genome:index_... [100%] 1 of 1 âœ”
[2b/b907ee] process > POREC:prepare_genome:index_... [100%] 1 of 1 âœ”
[39/92da21] process > POREC:digest_align_annotate... [100%] 1911 of 1911 âœ”
[-        ] process > POREC:haplotag_alignments      -
[5c/b4568d] process > POREC:merge_coordsorted_bam... [  0%] 0 of 1
[d2/2a86ee] process > POREC:merge_namesorted_bams... [  0%] 0 of 1
[a2/08f336] process > POREC:create_restriction_be... [100%] 1 of 1 âœ”
[32/ed1814] process > POREC:to_pairs_file (1911)     [100%] 1911 of 1911 âœ”
[87/221b10] process > POREC:merge_pairs (1)          [  0%] 0 of 1
[89/808b42] process > POREC:merge_pairs_stats (1)    [  0%] 0 of 1
[-        ] process > POREC:pair_stats_report        -
[d1/6bc236] process > POREC:getVersions              [100%] 1 of 1 âœ”
[cd/4df9fc] process > POREC:getParams                [100%] 1 of 1 âœ”
[d2/9014bc] process > POREC:makeReport (1)           [100%] 1 of 1 âœ”
[-        ] process > POREC:prepare_hic              -
ERROR ~ Error executing process > 'POREC:merge_pairs (1)'

Caused by:
  Process `POREC:merge_pairs (1)` terminated with an error exit status (1)

Command executed:

  pairtools merge -o "null.pairs.gz" --concatenate to_merge/src*.pairs.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (78) bind mounts
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pairtools", line 11, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 134, in merge
      merge_py(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 254, in merge_py
      subprocess.check_call(command, shell=True, stdout=outstream)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 359, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 7] Argument list too long: '/bin/sh'
  INFO:    Cleaning up image...

Work dir:
  /lustre/nobackup/WUR/ABGC/dieps003/9.4/work/87/221b100bc0e03aaaff4e37c94c62d3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

executor >  local (3834)
[d0/9a7cb2] process > POREC:fastcat (1)              [100%] 1 of 1 âœ”
[64/ddc92b] process > POREC:index_ubam (1)           [100%] 1 of 1 âœ”
[8d/fc3aec] process > POREC:prepare_genome:index_... [100%] 1 of 1 âœ”
[2b/b907ee] process > POREC:prepare_genome:index_... [100%] 1 of 1 âœ”
[39/92da21] process > POREC:digest_align_annotate... [100%] 1911 of 1911 âœ”
[-        ] process > POREC:haplotag_alignments      -
[5c/b4568d] process > POREC:merge_coordsorted_bam... [  0%] 0 of 1
[d2/2a86ee] process > POREC:merge_namesorted_bams... [  0%] 0 of 1
[a2/08f336] process > POREC:create_restriction_be... [100%] 1 of 1 âœ”
[32/ed1814] process > POREC:to_pairs_file (1911)     [100%] 1911 of 1911 âœ”
[87/221b10] process > POREC:merge_pairs (1)          [100%] 1 of 1, failed: 1 âœ˜
[89/808b42] process > POREC:merge_pairs_stats (1)    [  0%] 0 of 1
[-        ] process > POREC:pair_stats_report        -
[d1/6bc236] process > POREC:getVersions              [100%] 1 of 1 âœ”
[cd/4df9fc] process > POREC:getParams                [100%] 1 of 1 âœ”
[d2/9014bc] process > POREC:makeReport (1)           [100%] 1 of 1 âœ”
[-        ] process > POREC:prepare_hic              -
ERROR ~ Error executing process > 'POREC:merge_pairs (1)'

Caused by:
  Process `POREC:merge_pairs (1)` terminated with an error exit status (1)

Command executed:

  pairtools merge -o "null.pairs.gz" --concatenate to_merge/src*.pairs.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  WARNING: underlay of /etc/localtime required more than 50 (78) bind mounts
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pairtools", line 11, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 134, in merge
      merge_py(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 254, in merge_py
      subprocess.check_call(command, shell=True, stdout=outstream)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 359, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 7] Argument list too long: '/bin/sh'
  INFO:    Cleaning up image...

Work dir:
  /lustre/nobackup/WUR/ABGC/dieps003/9.4/work/87/221b100bc0e03aaaff4e37c94c62d3

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (3)

hopefully you are able to help me!

**Comment by cjw85** [comment]
Please reopen this issue using the Bur report issue type. Providing the requested information helps us to help you.
