### ISSUE TITLE
Process 'POREC:digest_align_annotate (1)' terminated with an error exit status (1)

### ISSUE THREAD

**Issue by malszycki** [epi2me-labs/wf-pore-c#39]
### Operating System

Other Linux (please specify below)

### Workflow Version

v0.2.0

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-pore-c  \
  --cutter 'NlaIII'  \
  --mcool_resolutions '10,20,30'  \
  --bam $ubam \
  --sample merged_SQK-NBD114-24_barcode01 \
  --ref hg38/ucsc/hg38.fa \
  --out_dir out_minimum \
  -profile singularity

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

workflow fails at digest_align_annotate.
seems, that it's cooler digest -o "fragments.bed"   "reference.fasta.fai" "reference.fasta"  NlaIII 
command that fails.
I ran the command outside of the container and it works with my cooler install

It seems, that workflow version v0.1.0 doesn't have this problem (running digest_align_annotate right now and it;s on 3%)

### Relevant log output

```shell
Process 'POREC:digest_align_annotate (1)' terminated with an error exit status (1)
(repeated in eternity)
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for reporting this. I will look in to this and get back to you.

**Comment by malszycki** [comment]
ERROR ~ Error executing process > 'POREC:create_restriction_bed (1)'

Caused by:
  Process `POREC:create_restriction_bed (1)` terminated with an error exit status (1)

Command executed:

  cooler digest -o "fragments.bed"   "reference.fasta.fai" "reference.fasta"  NlaIII

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    gocryptfs not found, will not be able to use gocryptfs
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 6, in <module>
      from cooler.cli import cli
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/__init__.py", line 12, in <module>
      from . import balance, create, fileops, parallel, tools
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/balance.py", line 8, in <module>
      from .parallel import partition, split
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/parallel.py", line 10, in <module>
      from .core import get
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/core/__init__.py", line 1, in <module>
      from ._rangequery import (
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/core/_rangequery.py", line 3, in <module>
      import pandas as pd
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
      from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/compat/__init__.py", line 18, in <module>
      from pandas.compat.numpy import (
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
      from pandas.util.version import Version
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/__init__.py", line 2, in <module>
      from pandas.util._decorators import (  # noqa:F401
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 14, in <module>
      from pandas._libs.properties import cache_readonly
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 13, in <module>
      from pandas._libs.interval import Interval
    File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
    File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
    File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/_libs/tslibs/__init__.py", line 37, in <module>
      from pandas._libs.tslibs.conversion import localize_pydatetime
    File "pandas/_libs/tslibs/conversion.pyx", line 77, in init pandas._libs.tslibs.conversion
    File "pandas/_libs/tslibs/parsing.pyx", line 38, in init pandas._libs.tslibs.parsing
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/dateutil/parser/__init__.py", line 2, in <module>
      from ._parser import parse, parser, parserinfo, ParserError
  MemoryError

Work dir:
  /scratch/local2/malszyck/test_v0.2.0/work/3f/e51164eb1c5a966a4efe294f151e3a

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
[c9/f7a2a3] NOTE: Process `POREC:digest_align_annotate (17)` terminated with an error exit status (1) -- Execution is retried (1)

**Comment by malszycki** [comment]
on retry it gives different error:
ERROR ~ Error executing process > 'POREC:create_restriction_bed (1)'

Caused by:
  Process `POREC:create_restriction_bed (1)` terminated with an error exit status (1)

Command executed:

  cooler digest -o "fragments.bed"   "reference.fasta.fai" "reference.fasta"  NlaIII

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    gocryptfs not found, will not be able to use gocryptfs
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/cooler", line 6, in <module>
      from cooler.cli import cli
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/__init__.py", line 12, in <module>
      from . import balance, create, fileops, parallel, tools
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/balance.py", line 8, in <module>
      from .parallel import partition, split
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/parallel.py", line 10, in <module>                                            from .core import get
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/core/__init__.py", line 1, in <module>
      from ._rangequery import (
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/cooler/core/_rangequery.py", line 3, in <module>
      import pandas as pd
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
      from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/compat/__init__.py", line 18, in <module>
      from pandas.compat.numpy import (
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
      from pandas.util.version import Version
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/__init__.py", line 2, in <module>
      from pandas.util._decorators import (  # noqa:F401
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 14, in <module>
      from pandas._libs.properties import cache_readonly
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/_libs/__init__.py", line 13, in <module>
      from pandas._libs.interval import Interval
    File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
    File "pandas/_libs/hashtable.pyx", line 1, in init pandas._libs.hashtable
    File "pandas/_libs/missing.pyx", line 1, in init pandas._libs.missing
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pandas/_libs/tslibs/__init__.py", line 37, in <module>
      from pandas._libs.tslibs.conversion import localize_pydatetime
    File "pandas/_libs/tslibs/conversion.pyx", line 77, in init pandas._libs.tslibs.conversion
    File "pandas/_libs/tslibs/parsing.pyx", line 1, in init pandas._libs.tslibs.parsing
    File "pandas/_libs/tslibs/offsets.pyx", line 36, in init pandas._libs.tslibs.offsets
  ImportError: /home/epi2melabs/conda/lib/python3.8/site-packages/pandas/_libs/properties.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
  .command.run: fork: Cannot allocate memory
  .command.run: line 158: kill: (37) - No such process

Work dir:
  /scratch/local2/malszyck/test_v0.2.0/work/0a/90e8b63e2d5faa6b044a40a05832ec

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by malszycki** [comment]
I don't think it's lack of memory:
$ mxvmem
  Memory: 1003.6 Gb available, 310.5 Gb in use (30.9 %)

**Comment by malszycki** [comment]
I converted dorado bam files into normal fastq with gatk SamToFastq and it seems to work without error (test datasets are working;  I'm running the full analysis right now - if it fails I'll update)

**Comment by malszycki** [comment]
Also I tried to run v0.1.1 on simplex basecalled reads with modifications and the workflow breaks at the same step. solution was to use fastq.

**Comment by sarahjeeeze** [comment]
Hi, to help me recreate your error can you clarify does the workflow seem to work at all with fastq or bam?  Or it breaks on both occasions. Could you try increasing the threads parameter to something like `--threads 8` and see if the workflow still breaks?

**Comment by sarahjeeeze** [comment]
Closing through lack of response, but let me know if issue persists.
