### ISSUE TITLE
Process `POREC:to_pairs_file` terminated with an error exit status (137)

### ISSUE THREAD

**Issue by Huan-Wei-hias** [epi2me-labs/wf-pore-c#49]
### Operating System

Other Linux (please specify below)

### Other Linux

Red Hat Enterprise Linux Server 7.6

### Workflow Version

nextflow 23.10.0

### Workflow Execution

Command line

### EPI2ME Version

v1.0.0

### CLI command run

nextflow run /sibcb2/liumofanglab2/lindihang/tools/porec/wf-pore-c-1.0.0 -c /sibcb2/liumofanglab2/lindihang/tools/porec/wf-pore-c-1.0.0/increase_memory.config \
--fastq /sibcb2/liumofanglab2/lindihang/data/20231109_bzy_porec_top2a/20231108/data/wt_pass.fq --chunk_size 10000 \
--ref /sibcb2/liumofanglab2/lindihang/reference/mm10/genome/ucsc/23-Jan-2020/mm10.fa \
--cutter NlaIII \
--paired_end_minimum_distance 100 --paired_end_maximum_distance 200 --hi_c --mcool --paired_end --threads 19

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Hello, thank you very much for your help last time (https://github.com/epi2me-labs/wf-pore-c/issues/43). Since resolving the issue last time, I reran the code and encountered a similar new issue, also an **Error 137**. It seems like a different script is experiencing the same problem.
 

The specific error details can be found in the '**Relevant log output**' section.

I tried modifying the **increase_memory.config** file as follows:
```
increase_memory.config file:
process {
    withName: makeReport {
        memory = "50 GB"
}
    withName: to_pairs_file {
        memory = "50 GB"
    }

}
```
I'm not sure if this will solve the problem. Moreover, my server runs quite slowly, and it would take about half a month to verify if the solution is effective.

Therefore, I would like to ask whether the modified script can solve the issue I encountered or if upgrading to the latest version v1.1.0 would prevent the problem from occurring?

### Relevant log output

```shell
executor >  local (10611)
[ed/173eac] process > POREC:fastcat (1)              [100%] 1 of 1 ✔
[99/161bee] process > POREC:index_bam (1)            [100%] 1 of 1 ✔
[95/36ead2] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[1f/e67267] process > POREC:digest_align_annotate... [ 87%] 4074 of 4654, fai...
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
[a7/24f753] process > POREC:create_restriction_be... [100%] 1 of 1 ✔
[9b/3ce98c] process > POREC:to_pairs_file (3259)     [ 79%] 3258 of 4073
[d7/e05c23] process > POREC:pairsToCooler (3258)     [100%] 3258 of 3258
[-        ] process > POREC:merge_mcools             -
[-        ] process > POREC:merge_pairs              -
[-        ] process > POREC:merge_pairs_stats        -
[-        ] process > POREC:pair_stats_report        -
[-        ] process > POREC:merge_paired_end_bams    -
[c6/42befa] process > POREC:getVersions              [100%] 1 of 1 ✔
[6f/77e07a] process > POREC:getParams                [100%] 1 of 1 ✔
[e3/0ca77c] process > POREC:makeReport               [100%] 1 of 1 ✔
[-        ] process > POREC:prepare_hic              -
[b2/1526ce] process > output (1)                     [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:to_pairs_file (3730)'

Caused by:
  Process `POREC:to_pairs_file (3730)` terminated with an error exit status (137)

Command executed:

  pairtools parse2      --output-stats "null.stats.txt"     -c "fasta.fai" --single-end --readid-transform 'readID.split(":")[0]'     --drop-sam --drop-seq --expand --add-pair-index --add-columns mapq,pos5,pos3,cigar,read_len,matched_bp,algn_ref_span,algn_read_span,dist_to_5,dist_to_3,mismatches "monomers.mm2.ns.bam" > extract_pairs.tmp
  pairtools restrict  -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp
  rm -rf extract_pairs.tmp

Command exit status:
  137

Command output:
  (empty)

Command error:
  [E::idx_find_and_load] Could not retrieve index file for 'monomers.mm2.ns.bam'
  .command.sh: line 3:   442 Killed                  pairtools restrict -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp

Work dir:
  /sibcb2/liumofanglab2/lindihang/project/01_cut_tag_porec/20231202_porec/code/ko/work/d6/fe3154c3abee16245dc01ba7a264c4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

executor >  local (10611)
[ed/173eac] process > POREC:fastcat (1)              [100%] 1 of 1 ✔
[99/161bee] process > POREC:index_bam (1)            [100%] 1 of 1 ✔
[95/36ead2] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[1f/e67267] process > POREC:digest_align_annotate... [ 87%] 4074 of 4654, fai...
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
[a7/24f753] process > POREC:create_restriction_be... [100%] 1 of 1 ✔
[d6/fe3154] process > POREC:to_pairs_file (3730)     [ 80%] 3259 of 4073, fai...
[d7/e05c23] process > POREC:pairsToCooler (3258)     [100%] 3258 of 3258
[-        ] process > POREC:merge_mcools             -
[-        ] process > POREC:merge_pairs              -
[-        ] process > POREC:merge_pairs_stats        -
[-        ] process > POREC:pair_stats_report        -
[-        ] process > POREC:merge_paired_end_bams    -
[c6/42befa] process > POREC:getVersions              [100%] 1 of 1 ✔
[6f/77e07a] process > POREC:getParams                [100%] 1 of 1 ✔
[e3/0ca77c] process > POREC:makeReport               [100%] 1 of 1 ✔
[-        ] process > POREC:prepare_hic              -
[b2/1526ce] process > output (1)                     [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:to_pairs_file (3730)'

Caused by:
  Process `POREC:to_pairs_file (3730)` terminated with an error exit status (137)

Command executed:

  pairtools parse2      --output-stats "null.stats.txt"     -c "fasta.fai" --single-end --readid-transform 'readID.split(":")[0]'     --drop-sam --drop-seq --expand --add-pair-index --add-columns mapq,pos5,pos3,cigar,read_len,matched_bp,algn_ref_span,algn_read_span,dist_to_5,dist_to_3,mismatches "monomers.mm2.ns.bam" > extract_pairs.tmp
  pairtools restrict  -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp
  rm -rf extract_pairs.tmp

Command exit status:
  137

Command output:
  (empty)

Command error:
  [E::idx_find_and_load] Could not retrieve index file for 'monomers.mm2.ns.bam'
  .command.sh: line 3:   442 Killed                  pairtools restrict -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp

Work dir:
  /sibcb2/liumofanglab2/lindihang/project/01_cut_tag_porec/20231202_porec/code/ko/work/d6/fe3154c3abee16245dc01ba7a264c4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

executor >  local (10611)
[ed/173eac] process > POREC:fastcat (1)              [100%] 1 of 1 ✔
[99/161bee] process > POREC:index_bam (1)            [100%] 1 of 1 ✔
[95/36ead2] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[1f/e67267] process > POREC:digest_align_annotate... [ 87%] 4074 of 4654, fai...
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   -
[-        ] process > POREC:merge_namesorted_bams    -
[a7/24f753] process > POREC:create_restriction_be... [100%] 1 of 1 ✔
[d6/fe3154] process > POREC:to_pairs_file (3730)     [ 80%] 3259 of 4073, fai...
[d7/e05c23] process > POREC:pairsToCooler (3258)     [100%] 3258 of 3258
[-        ] process > POREC:merge_mcools             -
[-        ] process > POREC:merge_pairs              -
[-        ] process > POREC:merge_pairs_stats        -
[-        ] process > POREC:pair_stats_report        -
[-        ] process > POREC:merge_paired_end_bams    -
[c6/42befa] process > POREC:getVersions              [100%] 1 of 1 ✔
[6f/77e07a] process > POREC:getParams                [100%] 1 of 1 ✔
[e3/0ca77c] process > POREC:makeReport               [100%] 1 of 1 ✔
[-        ] process > POREC:prepare_hic              -
[b2/1526ce] process > output (1)                     [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:to_pairs_file (3730)'

Caused by:
  Process `POREC:to_pairs_file (3730)` terminated with an error exit status (137)

Command executed:

  pairtools parse2      --output-stats "null.stats.txt"     -c "fasta.fai" --single-end --readid-transform 'readID.split(":")[0]'     --drop-sam --drop-seq --expand --add-pair-index --add-columns mapq,pos5,pos3,cigar,read_len,matched_bp,algn_ref_span,algn_read_span,dist_to_5,dist_to_3,mismatches "monomers.mm2.ns.bam" > extract_pairs.tmp
  pairtools restrict  -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp
  rm -rf extract_pairs.tmp

Command exit status:
  137

Command output:
  (empty)

Command error:
  [E::idx_find_and_load] Could not retrieve index file for 'monomers.mm2.ns.bam'
  .command.sh: line 3:   442 Killed                  pairtools restrict -f "fragments.bed" -o "null.pairs.gz" extract_pairs.tmp

Work dir:
  /sibcb2/liumofanglab2/lindihang/project/01_cut_tag_porec/20231202_porec/code/ko/work/d6/fe3154c3abee16245dc01ba7a264c4

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (12)
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by Huan-Wei-hias** [comment]
The method of modifying the file (**increase_memory.config**) still results in the same type of error: **Error 137**.
```
increase_memory.config file:
process {
    withName: makeReport {
        memory = "50 GB"
}
    withName: to_pairs_file {
        memory = "50 GB"
    }

}
```
Like this:
<img width="661" alt="image" src="https://github.com/epi2me-labs/wf-pore-c/assets/101387227/29ee7c14-7159-48ba-90c4-73377604a4f7">
How should I go about resolving this **Error 137**? I'm very much looking forward to your reply and assistance. Thank you!

**Comment by sarahjeeeze** [comment]
Hi, I notice you are using v1.0.0, perhaps try with v1.1.0 as we made some changes that should help with memory use of the digest_align_annotate step which may be leading to there not being enough memory for this step.

**Comment by Huan-Wei-hias** [comment]
Thank you very much for your response. I will try using the latest version to see if it resolves the issue. Here are the CPU and memory specifications of my server:
**CPUs:**
<img width="335" alt="36a5d84921e3f30fcc89318cf245ea5" src="https://github.com/epi2me-labs/wf-pore-c/assets/101387227/f4784c3c-4e28-41b0-8e35-4d6624b297e4">
**Memory:**
<img width="653" alt="b7b7f5a96be38114fd7654faa15f8bd" src="https://github.com/epi2me-labs/wf-pore-c/assets/101387227/d48c9ae8-191f-4aa2-b00c-3751d0054074">

**Comment by Huan-Wei-hias** [comment]
Today, I revisited the latest version to conduct my analysis, but unfortunately, I encountered the exact same 137 error (https://github.com/epi2me-labs/wf-pore-c/issues/43), where '**makeReport**' indicated insufficient memory. Does this suggest that the latest code update also fails to address this error?
<img width="671" alt="fe62a3b90f07477483d159d2a8a3699" src="https://github.com/epi2me-labs/wf-pore-c/assets/101387227/2a9ad0ce-cdb4-48d8-9802-770f35c5c146">

**Comment by Huan-Wei-hias** [comment]
I switched to a new snode, which has more available memory, and the issue I just mentioned has been resolved (https://github.com/epi2me-labs/wf-pore-c/issues/43). I will delve further to see if the new problem I've raised occurs again. Thank you very much for your selfless help and answers!
<img width="655" alt="c8de8f35b1c8dc9581d57976083c0c7" src="https://github.com/epi2me-labs/wf-pore-c/assets/101387227/2022eb60-5fd3-4eca-9228-89494359fe47">

**Comment by sarahjeeeze** [comment]
Hi, is this now resolved?

**Comment by Huan-Wei-hias** [comment]
Hello, I'm still unable to resolve the issue. Although reprocessing allowed the **to_pairs_file** to reach 100% completion, I'm encountering a memory shortage problem during the **merge_cools** step. It seems that running Pore-C requires a significant amount of memory. Would it be possible to optimize memory usage? I am currently in touch with the server administrator to clear some disk space and then I'll attempt to run the process again to see if it completes successfully.

**Comment by sarahjeeeze** [comment]
what is the error message you get from the merge_cools step?

**Comment by Huan-Wei-hias** [comment]
The error message is consistent with the previous one. I have consulted with the server administrators, and they will allocate a fnode with more memory (1T) for me to analyze the data. I will attempt to see if this resolves the **E137** issue. Thank you very much for your help.
![image](https://github.com/epi2me-labs/wf-pore-c/assets/101387227/253d73c8-cf7b-492e-871f-0b403f21cc28)

**Comment by Huan-Wei-hias** [comment]
Hello,
When I run porec on this high-memory node, I still encounter the exact same issue as before. It errors out **during the merge step (to_merge/src999.cool),** indicating that this might not be an issue related to memory usage. Could there be other reasons that would lead to this error message?
```
executor >  local (11874)
[26/311061] process > POREC:fastcat (1)              [100%] 1 of 1 ✔
[8a/49a5ec] process > POREC:index_bam (1)            [100%] 1 of 1 ✔
[5b/04748d] process > POREC:prepare_genome:index_... [100%] 1 of 1 ✔
[0b/67f2d6] process > POREC:digest_align_annotate... [100%] 3953 of 3953 ✔
[-        ] process > POREC:haplotag_alignments      -
[-        ] process > POREC:merge_coordsorted_bams   [  0%] 0 of 1
[01/146099] process > POREC:merge_namesorted_bams... [  0%] 0 of 1
[96/5a4be6] process > POREC:create_restriction_be... [100%] 1 of 1 ✔
[70/2df755] process > POREC:to_pairs_file (3951)     [100%] 3953 of 3953 ✔
[5e/bcda91] process > POREC:pairsToCooler (3953)     [100%] 3953 of 3953 ✔
[3c/5f796c] process > POREC:merge_mcools (1)         [  0%] 0 of 1
[7e/362f2d] process > POREC:merge_pairs (1)          [  0%] 0 of 1
[b4/5862e2] process > POREC:merge_pairs_stats (1)    [100%] 1 of 1 ✔
[fd/223de0] process > POREC:pair_stats_report (1)    [100%] 1 of 1 ✔
[96/553a47] process > POREC:merge_paired_end_bams... [  0%] 0 of 1
[b9/21d4af] process > POREC:getVersions              [100%] 1 of 1 ✔
[0a/7dd8dc] process > POREC:getParams                [100%] 1 of 1 ✔
[ce/e8c435] process > POREC:makeReport               [100%] 1 of 1 ✔
[-        ] process > POREC:prepare_hic              -
[68/b4f71f] process > POREC:get_filtered_out_bam (1) [  0%] 0 of 1
[86/348bc1] process > output (1)                     [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:merge_mcools (1)'

Caused by:
Process `POREC:merge_mcools (1)` terminated with an error exit status (137)

Command executed:

  cooler merge  null.cool   to_merge/src*.cool
  cooler zoomify -r 1000,2000,5000N -o null.mcool  null.cool

Command exit status:
  137

Command output:
  (empty)

Command error:
  to_merge/src959.cool
  to_merge/src96.cool
  to_merge/src960.cool
  to_merge/src961.cool
  to_merge/src962.cool
  to_merge/src963.cool
  to_merge/src964.cool
  to_merge/src965.cool
  to_merge/src966.cool
  to_merge/src967.cool
  to_merge/src968.cool
  to_merge/src969.cool
  to_merge/src97.cool
  to_merge/src970.cool
  to_merge/src971.cool
  to_merge/src972.cool
  to_merge/src973.cool
  to_merge/src974.cool
  to_merge/src975.cool
  to_merge/src976.cool
  to_merge/src977.cool
  to_merge/src978.cool
  to_merge/src979.cool
  to_merge/src98.cool
  to_merge/src980.cool
  to_merge/src981.cool
  to_merge/src982.cool
  to_merge/src983.cool
  to_merge/src984.cool
  to_merge/src985.cool
  to_merge/src986.cool
  to_merge/src987.cool
  to_merge/src988.cool
  to_merge/src989.cool
  to_merge/src99.cool
  to_merge/src990.cool
  to_merge/src991.cool
  to_merge/src992.cool
  to_merge/src993.cool
  to_merge/src994.cool
  to_merge/src995.cool
  to_merge/src996.cool
  to_merge/src997.cool
  to_merge/src998.cool
  to_merge/src999.cool
  INFO:cooler.create:Creating cooler at "null.cool::/"
  INFO:cooler.create:Writing chroms
  INFO:cooler.create:Writing bins
  INFO:cooler.create:Writing pixels
  .command.sh: line 2:    35 Killed                  cooler merge null.cool to_merge/src*.cool

Work dir:
  /sibcb2/liumofanglab2/lindihang/project/01_cut_tag_porec/20231202_porec/work/3c/5f796ca899b0
494daf3ced81e23228

Tip: when you have fixed the problem you can continue the execution adding the option `-resume
` to the run command line

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (4)

```

**Comment by Huan-Wei-hias** [comment]
We have reviewed the logs related to the kill process and have determined that the **Error 137** is indeed due to insufficient memory. By utilizing a node with larger memory, I didn't encounter the E137 error; however, I've come across a new bug, **Error 1**, which states "**[Errno 7] Argument list too long.**" 

It appears that there is **an issue with pairtools**; it seems to have a limitation on the number of files it can process. It looks like **the number of my pairs has exceeded its processing capacity**.

Could you please enlighten me on the possible cause and suggest how I might resolve it? 

I look forward to your response. Thank you!
```
executor >  local (11875)
[98/42e4b0] process > POREC:fastcat (1)                      [100%] 1 of 1 ✔
[a5/231bed] process > POREC:index_bam (1)                    [100%] 1 of 1 ✔
[45/596517] process > POREC:prepare_genome:index_ref_mmi (1) [100%] 1 of 1 ✔
[75/74c632] process > POREC:digest_align_annotate (3932)     [100%] 3953 of 3953 ✔
[-        ] process > POREC:haplotag_alignments              -
[5f/f0f90e] process > POREC:merge_coordsorted_bams (1)       [  0%] 0 of 1
[db/e12be4] process > POREC:merge_namesorted_bams (1)        [  0%] 0 of 1
[87/155319] process > POREC:create_restriction_bed (1)       [100%] 1 of 1 ✔
[e2/d12792] process > POREC:to_pairs_file (3953)             [100%] 3953 of 3953 ✔
[0c/a8f2b1] process > POREC:pairsToCooler (3952)             [100%] 3953 of 3953 ✔
[e9/812fc5] process > POREC:merge_mcools (1)                 [  0%] 0 of 1
[85/a17134] process > POREC:merge_pairs (1)                  [100%] 1 of 1, failed: 1 ✘
[33/55b86d] process > POREC:merge_pairs_stats (1)            [100%] 1 of 1 ✔
[af/c71913] process > POREC:pair_stats_report (1)            [100%] 1 of 1 ✔
[d4/70f157] process > POREC:merge_paired_end_bams (1)        [  0%] 0 of 1
[e4/a035d8] process > POREC:getVersions                      [100%] 1 of 1 ✔
[63/7af8d7] process > POREC:getParams                        [100%] 1 of 1 ✔
[72/0acb10] process > POREC:makeReport                       [100%] 1 of 1 ✔
[-        ] process > POREC:prepare_hic                      -
[8a/a90307] process > POREC:get_filtered_out_bam (1)         [  0%] 0 of 1
[e6/81496e] process > output (1)                             [100%] 1 of 1 ✔
ERROR ~ Error executing process > 'POREC:merge_pairs (1)'

Caused by:
  Process `POREC:merge_pairs (1)` terminated with an error exit status (1)

Command executed:

  # pass a quoted glob, pairtools will do its own globbing
  pairtools merge -o "null.pairs.gz" --concatenate 'to_merge/*'

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pairtools", line 11, in <module>
      sys.exit(cli())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
      return self.main(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1078, in main
      rv = self.invoke(ctx)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/click/core.py", line 783, in invoke
      return __callback(*args, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 134, in merge
      merge_py(
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pairtools/cli/merge.py", line 254, in merge_py
      subprocess.check_call(command, shell=True, stdout=outstream)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 359, in check_call
      retcode = call(*popenargs, **kwargs)
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 340, in call
      with Popen(*popenargs, **kwargs) as p:
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 858, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/epi2melabs/conda/lib/python3.8/subprocess.py", line 1720, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  OSError: [Errno 7] Argument list too long: '/bin/sh'

Work dir:
  /sibcb3/liumofanglab2/lindihang/project/01_cut_tag_porec/20231202_porec/workplace/wt/work/85/a17134d045c9914c2bca62aecf
4ea1

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.comma
nd.sh`

 -- Check '.nextflow.log' file for details
WARN: Killing running tasks (5)

```
