### ISSUE TITLE
[Bug]:  Process 'POREC:digest_align_annotate (1)' terminated with an error exit status (1)

### ISSUE THREAD

**Issue by sadhanagaddam3** [epi2me-labs/wf-pore-c#6]
### What happened?

I'm trying to run pore-c data generated in our lab on HPC cluster, I have merged all the pass folder fastq files and used it as input to run the wf-pore-c pipeline. Below is the error I end up with, could you please help me in fixing it?

Command used: 
./nextflow run epi2me-labs/wf-pore-c --fastq  porec_0423_CM_WT_passReads_combined.fastq --ref genome.fa --out_dir porec_CM_WT_0423 --coverage --chromunity --chromunity_merge_distance 25000 --pairs --mcool --cool_bin_size 1000 --cutter 'NlaIII'

[wf_porec.out.txt](https://github.com/epi2me-labs/wf-pore-c/files/11340475/wf_porec.out.txt)

Error executing process > 'POREC:digest_align_annotate (1)'

Caused by:
  Process `POREC:digest_align_annotate (1)` terminated with an error exit status (1)

Command executed:

  pore-c-py digest "concatemers.bam" "NlaIII" --header "concatemers.bam"             --threads 1 | 
  samtools fastq --threads 1 -T '*' |
  minimap2 -ay -t 2 -x map-ont             "reference.fasta.mmi" - |
  pore-c-py annotate - "porec_0423_CM_WT_passReads_combined" --monomers             --threads 1  --stdout true  --chromunity --chromunity_merge_distance 25000  |             tee "porec_0423_CM_WT_passReads_combined_out.ns.bam" |
  samtools sort -m 1G --threads 1  -u --write-index -o "porec_0423_CM_WT_passReads_combined.cs.bam" -

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
  INFO:    underlay of /etc/localtime required more than 50 (78) bind mounts
  [23:21:29 - AnntateBAM] Processing reads from -
  [23:21:29 - Digest    ] Digesting concatemers from [PosixPath('concatemers.bam')].
  [23:21:29 - Digest    ] Digesting unaligned sequences from <pysam.libcalignmentfile.AlignmentFile object at 0x7f5b6c3f54c0>
  [M::main::8.341*0.99] loaded/built the index for 195 target sequence(s)
  [M::mm_mapopt_update::10.757*0.99] mid_occ = 694
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 195
  [M::mm_idx_stat::11.905*0.99] distinct minimizers: 100167746 (38.80% are singletons); average occurrences: 5.519; average spacing: 5.607; total length: 3099922541
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pore-c-py", line 10, in <module>
      sys.exit(run_main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 382, in run_main
      args.func(args)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 295, in annotate_bam
      chrom_writer.write(concat_walk)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/writers.py", line 110, in write
      pylist = self.get_pylist(alignments)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/writers.py", line 90, in get_pylist
      if not block[0].is_unmapped:
  AttributeError: 'int' object has no attribute 'is_unmapped'
  [E::bgzf_flush] File write failed (wrong size)
  [E::bgzf_close] File write failed
  Traceback (most recent call last):
    File "/home/epi2melabs/conda/bin/pore-c-py", line 10, in <module>
      sys.exit(run_main())
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 382, in run_main
      args.func(args)
    File "/home/epi2melabs/conda/lib/python3.8/site-packages/pore_c_py/main.py", line 235, in digest_bam
      outbam.write(monomer)
    File "pysam/libcalignmentfile.pyx", line 1709, in pysam.libcalignmentfile.AlignmentFile.write
    File "pysam/libcalignmentfile.pyx", line 1741, in pysam.libcalignmentfile.AlignmentFile.write
  OSError: sam_write1 failed with error code -1

Work dir:
work/a6/c87d733233ca4dc62cf329a962098e

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

v0.0.3

### Relevant log output

```shell
NA
```

**Comment by ccneko** [comment]
Any comments? I am experiencing a similar error. Thank you.

**Comment by sarahjeeeze** [comment]
Hi, thanks for letting us know. This error should be fixed in the latest v0.0.4.

**Comment by ccneko** [comment]
Thank you Sarah and your team for the prompt support!

**Comment by sadhanagaddam3** [comment]
Thank you for getting back to us regarding the issue. May I know when will the latest version be released?

**Comment by cjw85** [comment]
v0.0.4 was released last Wednesday.
