### ISSUE TITLE
Error in test run

### ISSUE THREAD

**Issue by dnaase** [epi2me-labs/wf-pore-c#61]
### Operating System

CentOS 7

### Workflow Version

v24.04.2

### Workflow Execution

Command line

### CLI command run

nextflow run epi2me-labs/wf-pore-c \
--bam wf-pore-c-demo/porec_test.concatemers.bam --chunk_size 100 \
--ref wf-pore-c-demo/porec_test.fasta \
--cutter NlaIII \
--vcf wf-pore-c-demo/porec_test.phased_variants.vcf.gz \
--paired_end_minimum_distance 100 --paired_end_maximum_distance 200 --hi_c --mcool --paired_end

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

It report bugs with the following msg:

 N E X T F L O W   ~  version 24.04.2

Launching `https://github.com/epi2me-labs/wf-pore-c` [hopeful_pike] DSL2 - revision: a4ffadaaa9 [master]

ERROR ~ Script compilation error
- file : /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf
- cause: Invalid output definition @ line 386, column 5.
       output(POREC.out.stats)
       ^

1 error

 -- Check '.nextflow.log' file for details

### Relevant log output

```shell
N E X T F L O W   ~  version 24.04.2

Launching `https://github.com/epi2me-labs/wf-pore-c` [hopeful_pike] DSL2 - revision: a4ffadaaa9 [master]

Jun-04 10:56:24.450 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-pore-c --bam wf-pore-c-demo/porec_test.concatemers.bam --chunk_size 100 --ref wf-pore-c-demo/porec_test.fasta --cutter NlaIII --vcf wf-pore-c-demo/porec_test.phased_variants.vcf.gz --paired_end_minimum_distance 100 --paired_end_maximum_distance 200 --hi_c --mcool --paired_end
Jun-04 10:56:24.561 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.2
Jun-04 10:56:24.583 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/xfj2191/.nextflow/plugins; core-plugins: nf-amazon@2.5.2,nf-azure@1.6.0,nf-cloudcache@0.4.1,nf-codecommit@0.2.0,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2,nf-tower@1.9.1,nf-wave@1.4.2
Jun-04 10:56:24.594 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jun-04 10:56:24.595 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jun-04 10:56:24.599 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.10.0 in 'deployment' mode
Jun-04 10:56:24.611 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jun-04 10:56:24.624 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/xfj2191/.nextflow/scm
Jun-04 10:56:25.494 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-pore-c.git
Jun-04 10:56:25.525 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Jun-04 10:56:25.535 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-pore-c.git
Jun-04 10:56:26.250 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config
Jun-04 10:56:26.253 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/nextflow.config
Jun-04 10:56:26.263 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/xfj2191/.nextflow/secrets/store.json
Jun-04 10:56:26.265 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@5ed5b321] - activable => nextflow.secret.LocalSecretsProvider@5ed5b321
Jun-04 10:56:26.278 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Jun-04 10:56:26.522 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declaration
Jun-04 10:56:26.523 [main] DEBUG nextflow.cli.CmdRun - Launching `https://github.com/epi2me-labs/wf-pore-c` [voluminous_perlman] DSL2 - revision: a4ffadaaa9 [master]
Jun-04 10:56:26.524 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jun-04 10:56:26.524 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jun-04 10:56:26.580 [main] DEBUG nextflow.Session - Session UUID: 08a9842c-b27c-4619-9f10-a685d1451028
Jun-04 10:56:26.581 [main] DEBUG nextflow.Session - Run name: voluminous_perlman
Jun-04 10:56:26.581 [main] DEBUG nextflow.Session - Executor pool size: 5
Jun-04 10:56:26.590 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Jun-04 10:56:26.594 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=15; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jun-04 10:56:26.614 [main] DEBUG nextflow.cli.CmdRun -
  Version: 24.04.2 build 5914
  Created: 29-05-2024 06:19 UTC (01:19 CDT)
  System: Linux 3.10.0-1160.95.1.el7.x86_64
  Runtime: Groovy 4.0.21 on OpenJDK 64-Bit Server VM 17.0.2+8
  Encoding: UTF-8 (ANSI_X3.4-1968)
  Process: 66723@qnode0137 [172.20.138.37]
  CPUs: 5 - Mem: 20 GB (19.7 GB) - Swap: 0 (0)
Jun-04 10:56:26.635 [main] DEBUG nextflow.Session - Work-dir: /projects/b1198/epifluidlab/yaping/projects/porec_gm_20240602/test/work [gpfs]
Jun-04 10:56:26.720 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jun-04 10:56:26.732 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jun-04 10:56:26.795 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jun-04 10:56:26.804 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 6; maxThreads: 1000
Jun-04 10:56:26.929 [main] DEBUG nextflow.Session - Session start
Jun-04 10:56:26.935 [main] DEBUG nextflow.trace.TraceFileObserver - Workflow started -- trace file: /projects/b1198/epifluidlab/yaping/projects/porec_gm_20240602/test/output/execution/trace.txt
Jun-04 10:56:26.966 [main] DEBUG nextflow.Session - Using default localLib path: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/lib
Jun-04 10:56:26.975 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/lib
Jun-04 10:56:26.976 [main] DEBUG nextflow.Session - Adding to the classpath library: /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/lib/nfcore_external_java_deps.jar
Jun-04 10:56:27.869 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
Jun-04 10:56:27.875 [main] ERROR nextflow.cli.Launcher - Script compilation error
- file : /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf
- cause: Invalid output definition @ line 386, column 5.
       output(POREC.out.stats)
       ^

1 error

nextflow.exception.ScriptCompilationException: Script compilation error
- file : /home/xfj2191/.nextflow/assets/epi2me-labs/wf-pore-c/main.nf
- cause: Invalid output definition @ line 386, column 5.
       output(POREC.out.stats)
       ^

1 error

        at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:196)
        at nextflow.script.ScriptParser.parse(ScriptParser.groovy:206)
        at nextflow.script.ScriptRunner.parseScript(ScriptRunner.groovy:229)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:136)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:372)
        at nextflow.cli.Launcher.run(Launcher.groovy:503)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script_6183ff06cb5d1fd0: 386: Invalid output definition @ line 386, column 5.
       output(POREC.out.stats)
       ^

1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:292)
        at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:980)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyShell.parseClass(GroovyShell.java:572)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:585)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:639)
        at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
        at nextflow.script.ScriptParser.parse0(ScriptParser.groovy:175)
        ... 6 common frames omitted
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

### Other demo data information

```shell
wf-pore-c-demo.tar.gz
```

**Comment by sarahjeeeze** [comment]
Hi, thanks for reporting this, this workflow is untested with the latest version of nextflow we have a fix coming soon. In the meantime you could run it with 23.04.2

**Comment by dnaase** [comment]
It works now! Thanks a lot!
